name: Run Export Script Twice Daily

on:
  schedule:
    - cron: '0 */12 * * *'    # ogni 12 ore allo scoccare del minuto 0 (UTC): 00:00 e 12:00
  workflow_dispatch:         # permette esecuzione manuale

jobs:
  run-export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run export script
        run: python news_fetcher.py
